import { Apartment } from "../app/utils/types";

export const rawApartments: Apartment[] = [
  {
    apartmentId: "W11_001",
    address: "Baarermatte, 6340 Baar",
    factsheet: "",
    incidentalCosts: 90,
    state: "frei",
    moveInDate: null,
    floor: "EG",
    floorNum: 0,
    priceUnit: "CHF",
    rentalPrice: 2000,
    rentalPriceSquaremeterNet: 0,
    rentalPriceSquaremeter: 0,
    title: "W11_001",
    name: "11.001",
    rooms: 2.5,
    area: 67,
    virtualTourLink: "",
    balcony: 0,
    loggiaArea: 0,
    gardenSittingPlaceArea: 12,
    terraceArea: 0,
    basementArea: 10,
    parkingSpaceCost: 0,
    deposit: 0,
    reduitArea: 0,
    referenceNumber: "11.001",
  },
  {
    apartmentId: "W11_002",
    address: "Baarermatte, 6340 Baar",
    factsheet: "",
    incidentalCosts: 90,
    state: "frei",
    moveInDate: null,
    floor: "EG",
    floorNum: 0,
    priceUnit: "CHF",
    rentalPrice: 2000,
    rentalPriceSquaremeterNet: 0,
    rentalPriceSquaremeter: 0,
    title: "W11_002",
    name: "11.002",
    rooms: 2.5,
    area: 67,
    virtualTourLink: "",
    balcony: 0,
    loggiaArea: 0,
    gardenSittingPlaceArea: 12,
    terraceArea: 0,
    basementArea: 10,
    parkingSpaceCost: 0,
    deposit: 0,
    reduitArea: 0,
    referenceNumber: "11.002",
  },
  {
    apartmentId: "W12_002",
    address: "Baarermatte, 6340 Baar",
    factsheet: "",
    incidentalCosts: 90,
    state: "frei",
    moveInDate: null,
    floor: "EG",
    floorNum: 0,
    priceUnit: "CHF",
    rentalPrice: 2000,
    rentalPriceSquaremeterNet: 0,
    rentalPriceSquaremeter: 0,
    title: "W12_002",
    name: "12.002",
    rooms: 2.5,
    area: 67,
    virtualTourLink: "",
    balcony: 0,
    loggiaArea: 0,
    gardenSittingPlaceArea: 12,
    terraceArea: 0,
    basementArea: 10,
    parkingSpaceCost: 0,
    deposit: 0,
    reduitArea: 0,
    referenceNumber: "12.002",
  },
  {
    apartmentId: "W13_001",
    address: "Baarermatte, 6340 Baar",
    factsheet: "",
    incidentalCosts: 90,
    state: "frei",
    moveInDate: null,
    floor: "EG",
    floorNum: 0,
    priceUnit: "CHF",
    rentalPrice: 2000,
    rentalPriceSquaremeterNet: 0,
    rentalPriceSquaremeter: 0,
    title: "W13_001",
    name: "13.001",
    rooms: 2.5,
    area: 67,
    virtualTourLink: "",
    balcony: 0,
    loggiaArea: 0,
    gardenSittingPlaceArea: 12,
    terraceArea: 0,
    basementArea: 10,
    parkingSpaceCost: 0,
    deposit: 0,
    reduitArea: 0,
    referenceNumber: "13.001",
  },
  {
    apartmentId: "W13_002",
    address: "Baarermatte, 6340 Baar",
    factsheet: "",
    incidentalCosts: 90,
    state: "frei",
    moveInDate: null,
    floor: "EG",
    floorNum: 0,
    priceUnit: "CHF",
    rentalPrice: 2000,
    rentalPriceSquaremeterNet: 0,
    rentalPriceSquaremeter: 0,
    title: "W13_002",
    name: "13.002",
    rooms: 2.5,
    area: 67,
    virtualTourLink: "",
    balcony: 0,
    loggiaArea: 0,
    gardenSittingPlaceArea: 12,
    terraceArea: 0,
    basementArea: 10,
    parkingSpaceCost: 0,
    deposit: 0,
    reduitArea: 0,
    referenceNumber: "13.002",
  },
  {
    apartmentId: "W11_102",
    address: "Baarermatte, 6340 Baar",
    factsheet: "",
    incidentalCosts: 90,
    state: "frei",
    moveInDate: null,
    floor: "1.OG",
    floorNum: 1,
    priceUnit: "CHF",
    rentalPrice: 2200,
    rentalPriceSquaremeterNet: 0,
    rentalPriceSquaremeter: 0,
    title: "W11_102",
    name: "11.102",
    rooms: 2.5,
    area: 67,
    virtualTourLink: "",
    balcony: 12,
    loggiaArea: 0,
    gardenSittingPlaceArea: 0,
    terraceArea: 0,
    basementArea: 10,
    parkingSpaceCost: 0,
    deposit: 0,
    reduitArea: 0,
    referenceNumber: "11.102",
  },
  {
    apartmentId: "W12_101",
    address: "Baarermatte, 6340 Baar",
    factsheet: "",
    incidentalCosts: 90,
    state: "frei",
    moveInDate: null,
    floor: "1.OG",
    floorNum: 1,
    priceUnit: "CHF",
    rentalPrice: 2200,
    rentalPriceSquaremeterNet: 0,
    rentalPriceSquaremeter: 0,
    title: "W12_101",
    name: "12.101",
    rooms: 2.5,
    area: 67,
    virtualTourLink: "",
    balcony: 12,
    loggiaArea: 0,
    gardenSittingPlaceArea: 0,
    terraceArea: 0,
    basementArea: 10,
    parkingSpaceCost: 0,
    deposit: 0,
    reduitArea: 0,
    referenceNumber: "12.101",
  },
  {
    apartmentId: "W12_102",
    address: "Baarermatte, 6340 Baar",
    factsheet: "",
    incidentalCosts: 90,
    state: "frei",
    moveInDate: null,
    floor: "1.OG",
    floorNum: 1,
    priceUnit: "CHF",
    rentalPrice: 2200,
    rentalPriceSquaremeterNet: 0,
    rentalPriceSquaremeter: 0,
    title: "W12_102",
    name: "12.102",
    rooms: 2.5,
    area: 67,
    virtualTourLink: "",
    balcony: 12,
    loggiaArea: 0,
    gardenSittingPlaceArea: 0,
    terraceArea: 0,
    basementArea: 10,
    parkingSpaceCost: 0,
    deposit: 0,
    reduitArea: 0,
    referenceNumber: "12.102",
  },

  {
    apartmentId: "W13_102",
    address: "Baarermatte, 6340 Baar",
    factsheet: "",
    incidentalCosts: 90,
    state: "frei",
    moveInDate: null,
    floor: "1.OG",
    floorNum: 1,
    priceUnit: "CHF",
    rentalPrice: 2200,
    rentalPriceSquaremeterNet: 0,
    rentalPriceSquaremeter: 0,
    title: "W13_102",
    name: "13.102",
    rooms: 2.5,
    area: 67,
    virtualTourLink: "",
    balcony: 12,
    loggiaArea: 0,
    gardenSittingPlaceArea: 0,
    terraceArea: 0,
    basementArea: 10,
    parkingSpaceCost: 0,
    deposit: 0,
    reduitArea: 0,
    referenceNumber: "13.102",
  },
  {
    apartmentId: "W11_202",
    address: "Baarermatte, 6340 Baar",
    factsheet: "",
    incidentalCosts: 90,
    state: "frei",
    moveInDate: null,
    floor: "2.OG",
    floorNum: 2,
    priceUnit: "CHF",
    rentalPrice: 2300,
    rentalPriceSquaremeterNet: 0,
    rentalPriceSquaremeter: 0,
    title: "W11_202",
    name: "11.202",
    rooms: 2.5,
    area: 67,
    virtualTourLink: "",
    balcony: 12,
    loggiaArea: 0,
    gardenSittingPlaceArea: 0,
    terraceArea: 0,
    basementArea: 10,
    parkingSpaceCost: 0,
    deposit: 0,
    reduitArea: 0,
    referenceNumber: "11.202",
  },
  {
    apartmentId: "W12_201",
    address: "Baarermatte, 6340 Baar",
    factsheet: "",
    incidentalCosts: 90,
    state: "frei",
    moveInDate: null,
    floor: "2.OG",
    floorNum: 2,
    priceUnit: "CHF",
    rentalPrice: 2300,
    rentalPriceSquaremeterNet: 0,
    rentalPriceSquaremeter: 0,
    title: "W12_201",
    name: "12.201",
    rooms: 2.5,
    area: 67,
    virtualTourLink: "",
    balcony: 12,
    loggiaArea: 0,
    gardenSittingPlaceArea: 0,
    terraceArea: 0,
    basementArea: 10,
    parkingSpaceCost: 0,
    deposit: 0,
    reduitArea: 0,
    referenceNumber: "12.201",
  },
  {
    apartmentId: "W12_202",
    address: "Baarermatte, 6340 Baar",
    factsheet: "",
    incidentalCosts: 90,
    state: "frei",
    moveInDate: null,
    floor: "2.OG",
    floorNum: 2,
    priceUnit: "CHF",
    rentalPrice: 2300,
    rentalPriceSquaremeterNet: 0,
    rentalPriceSquaremeter: 0,
    title: "W12_202",
    name: "12.202",
    rooms: 2.5,
    area: 67,
    virtualTourLink: "",
    balcony: 12,
    loggiaArea: 0,
    gardenSittingPlaceArea: 0,
    terraceArea: 0,
    basementArea: 10,
    parkingSpaceCost: 0,
    deposit: 0,
    reduitArea: 0,
    referenceNumber: "12.202",
  },
  {
    apartmentId: "W13_101",
    address: "Baarermatte, 6340 Baar",
    factsheet: "",
    incidentalCosts: 90,
    state: "frei",
    moveInDate: null,
    floor: "2.OG",
    floorNum: 2,
    priceUnit: "CHF",
    rentalPrice: 2300,
    rentalPriceSquaremeterNet: 0,
    rentalPriceSquaremeter: 0,
    title: "W13_101",
    name: "13.101",
    rooms: 2.5,
    area: 67,
    virtualTourLink: "",
    balcony: 12,
    loggiaArea: 0,
    gardenSittingPlaceArea: 0,
    terraceArea: 0,
    basementArea: 10,
    parkingSpaceCost: 0,
    deposit: 0,
    reduitArea: 0,
    referenceNumber: "13.101",
  },
  {
    apartmentId: "W13_202",
    address: "Baarermatte, 6340 Baar",
    factsheet: "",
    incidentalCosts: 90,
    state: "frei",
    moveInDate: null,
    floor: "2.OG",
    floorNum: 2,
    priceUnit: "CHF",
    rentalPrice: 2300,
    rentalPriceSquaremeterNet: 0,
    rentalPriceSquaremeter: 0,
    title: "W13_202",
    name: "13.202",
    rooms: 2.5,
    area: 67,
    virtualTourLink: "",
    balcony: 12,
    loggiaArea: 0,
    gardenSittingPlaceArea: 0,
    terraceArea: 0,
    basementArea: 10,
    parkingSpaceCost: 0,
    deposit: 0,
    reduitArea: 0,
    referenceNumber: "13.202",
  },
  {
    apartmentId: "W11_302",
    address: "Baarermatte, 6340 Baar",
    factsheet: "",
    incidentalCosts: 90,
    state: "frei",
    moveInDate: null,
    floor: "3.OG",
    floorNum: 3,
    priceUnit: "CHF",
    rentalPrice: 2400,
    rentalPriceSquaremeterNet: 0,
    rentalPriceSquaremeter: 0,
    title: "W11_302",
    name: "11.302",
    rooms: 3.5,
    area: 67,
    virtualTourLink: "",
    balcony: 12,
    loggiaArea: 0,
    gardenSittingPlaceArea: 0,
    terraceArea: 0,
    basementArea: 10,
    parkingSpaceCost: 0,
    deposit: 0,
    reduitArea: 0,
    referenceNumber: "11.302",
  },
  {
    apartmentId: "W12_301",
    address: "Baarermatte, 6340 Baar",
    factsheet: "",
    incidentalCosts: 90,
    state: "frei",
    moveInDate: null,
    floor: "3.OG",
    floorNum: 3,
    priceUnit: "CHF",
    rentalPrice: 2400,
    rentalPriceSquaremeterNet: 0,
    rentalPriceSquaremeter: 0,
    title: "W12_301",
    name: "12.301",
    rooms: 3.5,
    area: 67,
    virtualTourLink: "",
    balcony: 12,
    loggiaArea: 0,
    gardenSittingPlaceArea: 0,
    terraceArea: 0,
    basementArea: 10,
    parkingSpaceCost: 0,
    deposit: 0,
    reduitArea: 0,
    referenceNumber: "12.301",
  },
  {
    apartmentId: "W12_302",
    address: "Baarermatte, 6340 Baar",
    factsheet: "",
    incidentalCosts: 90,
    state: "frei",
    moveInDate: null,
    floor: "3.OG",
    floorNum: 3,
    priceUnit: "CHF",
    rentalPrice: 2400,
    rentalPriceSquaremeterNet: 0,
    rentalPriceSquaremeter: 0,
    title: "W12_302",
    name: "12.302",
    rooms: 3.5,
    area: 67,
    virtualTourLink: "",
    balcony: 12,
    loggiaArea: 0,
    gardenSittingPlaceArea: 0,
    terraceArea: 0,
    basementArea: 10,
    parkingSpaceCost: 0,
    deposit: 0,
    reduitArea: 0,
    referenceNumber: "12.302",
  },
  {
    apartmentId: "W13_301",
    address: "Baarermatte, 6340 Baar",
    factsheet: "",
    incidentalCosts: 90,
    state: "frei",
    moveInDate: null,
    floor: "3.OG",
    floorNum: 3,
    priceUnit: "CHF",
    rentalPrice: 2400,
    rentalPriceSquaremeterNet: 0,
    rentalPriceSquaremeter: 0,
    title: "W12_301",
    name: "12.301",
    rooms: 3.5,
    area: 67,
    virtualTourLink: "",
    balcony: 12,
    loggiaArea: 0,
    gardenSittingPlaceArea: 0,
    terraceArea: 0,
    basementArea: 10,
    parkingSpaceCost: 0,
    deposit: 0,
    reduitArea: 0,
    referenceNumber: "12.301",
  },
  {
    apartmentId: "W13_302",
    address: "Baarermatte, 6340 Baar",
    factsheet: "",
    incidentalCosts: 90,
    state: "frei",
    moveInDate: null,
    floor: "3.OG",
    floorNum: 3,
    priceUnit: "CHF",
    rentalPrice: 2400,
    rentalPriceSquaremeterNet: 0,
    rentalPriceSquaremeter: 0,
    title: "W12_302",
    name: "12.302",
    rooms: 3.5,
    area: 67,
    virtualTourLink: "",
    balcony: 12,
    loggiaArea: 0,
    gardenSittingPlaceArea: 0,
    terraceArea: 0,
    basementArea: 10,
    parkingSpaceCost: 0,
    deposit: 0,
    reduitArea: 0,
    referenceNumber: "12.302",
  },
  {
    apartmentId: "W11_402",
    address: "Baarermatte, 6340 Baar",
    factsheet: "",
    incidentalCosts: 90,
    state: "frei",
    moveInDate: null,
    floor: "4.OG",
    floorNum: 4,
    priceUnit: "CHF",
    rentalPrice: 2550,
    rentalPriceSquaremeterNet: 0,
    rentalPriceSquaremeter: 0,
    title: "W12_402",
    name: "12.402",
    rooms: 3.5,
    area: 67,
    virtualTourLink: "",
    balcony: 12,
    loggiaArea: 0,
    gardenSittingPlaceArea: 0,
    terraceArea: 0,
    basementArea: 10,
    parkingSpaceCost: 0,
    deposit: 0,
    reduitArea: 0,
    referenceNumber: "12.402",
  },
  {
    apartmentId: "W12_401",
    address: "Baarermatte, 6340 Baar",
    factsheet: "",
    incidentalCosts: 90,
    state: "frei",
    moveInDate: null,
    floor: "4.OG",
    floorNum: 4,
    priceUnit: "CHF",
    rentalPrice: 2550,
    rentalPriceSquaremeterNet: 0,
    rentalPriceSquaremeter: 0,
    title: "W12_401",
    name: "12.401",
    rooms: 3.5,
    area: 67,
    virtualTourLink: "",
    balcony: 12,
    loggiaArea: 0,
    gardenSittingPlaceArea: 0,
    terraceArea: 0,
    basementArea: 10,
    parkingSpaceCost: 0,
    deposit: 0,
    reduitArea: 0,
    referenceNumber: "12.401",
  },
  {
    apartmentId: "W12_402",
    address: "Baarermatte, 6340 Baar",
    factsheet: "",
    incidentalCosts: 90,
    state: "frei",
    moveInDate: null,
    floor: "4.OG",
    floorNum: 4,
    priceUnit: "CHF",
    rentalPrice: 2550,
    rentalPriceSquaremeterNet: 0,
    rentalPriceSquaremeter: 0,
    title: "W12_402",
    name: "12.402",
    rooms: 3.5,
    area: 80,
    virtualTourLink: "",
    balcony: 12,
    loggiaArea: 0,
    gardenSittingPlaceArea: 0,
    terraceArea: 0,
    basementArea: 10,
    parkingSpaceCost: 0,
    deposit: 0,
    reduitArea: 0,
    referenceNumber: "12.402",
  },
  {
    apartmentId: "W13_401",
    address: "Baarermatte, 6340 Baar",
    factsheet: "",
    incidentalCosts: 90,
    state: "frei",
    moveInDate: null,
    floor: "4.OG",
    floorNum: 4,
    priceUnit: "CHF",
    rentalPrice: 2550,
    rentalPriceSquaremeterNet: 0,
    rentalPriceSquaremeter: 0,
    title: "W13_401",
    name: "13.401",
    rooms: 3.5,
    area: 80,
    virtualTourLink: "",
    balcony: 12,
    loggiaArea: 0,
    gardenSittingPlaceArea: 0,
    terraceArea: 0,
    basementArea: 10,
    parkingSpaceCost: 0,
    deposit: 0,
    reduitArea: 0,
    referenceNumber: "13.401",
  },
  {
    apartmentId: "W13_402",
    address: "Baarermatte, 6340 Baar",
    factsheet: "",
    incidentalCosts: 90,
    state: "frei",
    moveInDate: null,
    floor: "4.OG",
    floorNum: 4,
    priceUnit: "CHF",
    rentalPrice: 2550,
    rentalPriceSquaremeterNet: 0,
    rentalPriceSquaremeter: 0,
    title: "W13_402",
    name: "13.402",
    rooms: 3.5,
    area: 80,
    virtualTourLink: "",
    balcony: 12,
    loggiaArea: 0,
    gardenSittingPlaceArea: 0,
    terraceArea: 0,
    basementArea: 10,
    parkingSpaceCost: 0,
    deposit: 0,
    reduitArea: 0,
    referenceNumber: "13.402",
  },
  {
    apartmentId: "W11_501",
    address: "Baarermatte, 6340 Baar",
    factsheet: "",
    incidentalCosts: 90,
    state: "frei",
    moveInDate: null,
    floor: "5.OG",
    floorNum: 5,
    priceUnit: "CHF",
    rentalPrice: 2700,
    rentalPriceSquaremeterNet: 0,
    rentalPriceSquaremeter: 0,
    title: "W11_501",
    name: "11.501",
    rooms: 4.5,
    area: 100,
    virtualTourLink: "",
    balcony: 12,
    loggiaArea: 0,
    gardenSittingPlaceArea: 0,
    terraceArea: 0,
    basementArea: 10,
    parkingSpaceCost: 0,
    deposit: 0,
    reduitArea: 0,
    referenceNumber: "11.501",
  },
  {
    apartmentId: "W11_502",
    address: "Baarermatte, 6340 Baar",
    factsheet: "",
    incidentalCosts: 90,
    state: "frei",
    moveInDate: null,
    floor: "5.OG",
    floorNum: 5,
    priceUnit: "CHF",
    rentalPrice: 2700,
    rentalPriceSquaremeterNet: 0,
    rentalPriceSquaremeter: 0,
    title: "W11_502",
    name: "11.502",
    rooms: 4.5,
    area: 100,
    virtualTourLink: "",
    balcony: 12,
    loggiaArea: 0,
    gardenSittingPlaceArea: 0,
    terraceArea: 0,
    basementArea: 10,
    parkingSpaceCost: 0,
    deposit: 0,
    reduitArea: 0,
    referenceNumber: "11.502",
  },
  {
    apartmentId: "W12_501",
    address: "Baarermatte, 6340 Baar",
    factsheet: "",
    incidentalCosts: 90,
    state: "frei",
    moveInDate: null,
    floor: "5.OG",
    floorNum: 5,
    priceUnit: "CHF",
    rentalPrice: 2700,
    rentalPriceSquaremeterNet: 0,
    rentalPriceSquaremeter: 0,
    title: "W12_501",
    name: "12.501",
    rooms: 4.5,
    area: 100,
    virtualTourLink: "",
    balcony: 12,
    loggiaArea: 0,
    gardenSittingPlaceArea: 0,
    terraceArea: 0,
    basementArea: 10,
    parkingSpaceCost: 0,
    deposit: 0,
    reduitArea: 0,
    referenceNumber: "12.501",
  },
  {
    apartmentId: "W12_502",
    address: "Baarermatte, 6340 Baar",
    factsheet: "",
    incidentalCosts: 90,
    state: "frei",
    moveInDate: null,
    floor: "5.OG",
    floorNum: 5,
    priceUnit: "CHF",
    rentalPrice: 2700,
    rentalPriceSquaremeterNet: 0,
    rentalPriceSquaremeter: 0,
    title: "W12_502",
    name: "12.502",
    rooms: 4.5,
    area: 100,
    virtualTourLink: "",
    balcony: 12,
    loggiaArea: 0,
    gardenSittingPlaceArea: 0,
    terraceArea: 0,
    basementArea: 10,
    parkingSpaceCost: 0,
    deposit: 0,
    reduitArea: 0,
    referenceNumber: "12.502",
  },
  {
    apartmentId: "W13_501",
    address: "Baarermatte, 6340 Baar",
    factsheet: "",
    incidentalCosts: 90,
    state: "frei",
    moveInDate: null,
    floor: "5.OG",
    floorNum: 5,
    priceUnit: "CHF",
    rentalPrice: 2700,
    rentalPriceSquaremeterNet: 0,
    rentalPriceSquaremeter: 0,
    title: "W13_501",
    name: "13.501",
    rooms: 4.5,
    area: 100,
    virtualTourLink: "",
    balcony: 12,
    loggiaArea: 0,
    gardenSittingPlaceArea: 0,
    terraceArea: 0,
    basementArea: 10,
    parkingSpaceCost: 0,
    deposit: 0,
    reduitArea: 0,
    referenceNumber: "13.501",
  },
  {
    apartmentId: "W13_502",
    address: "Baarermatte, 6340 Baar",
    factsheet: "",
    incidentalCosts: 90,
    state: "frei",
    moveInDate: null,
    floor: "5.OG",
    floorNum: 5,
    priceUnit: "CHF",
    rentalPrice: 2700,
    rentalPriceSquaremeterNet: 0,
    rentalPriceSquaremeter: 0,
    title: "W13_502",
    name: "13.502",
    rooms: 4.5,
    area: 100,
    virtualTourLink: "",
    balcony: 12,
    loggiaArea: 0,
    gardenSittingPlaceArea: 0,
    terraceArea: 0,
    basementArea: 10,
    parkingSpaceCost: 0,
    deposit: 0,
    reduitArea: 0,
    referenceNumber: "13.502",
  },
  {
    apartmentId: "W21_001",
    address: "Baarermatte, 6340 Baar",
    factsheet: "",
    incidentalCosts: 90,
    state: "frei",
    moveInDate: null,
    floor: "EG",
    floorNum: 0,
    priceUnit: "CHF",
    rentalPrice: 1900,
    rentalPriceSquaremeterNet: 0,
    rentalPriceSquaremeter: 0,
    title: "W21_001",
    name: "21.001",
    rooms: 2.5,
    area: 67,
    virtualTourLink: "",
    balcony: 0,
    loggiaArea: 0,
    gardenSittingPlaceArea: 12,
    terraceArea: 0,
    basementArea: 10,
    parkingSpaceCost: 0,
    deposit: 0,
    reduitArea: 0,
    referenceNumber: "21.001",
  },
  {
    apartmentId: "W21_002",
    address: "Baarermatte, 6340 Baar",
    factsheet: "",
    incidentalCosts: 90,
    state: "frei",
    moveInDate: null,
    floor: "EG",
    floorNum: 0,
    priceUnit: "CHF",
    rentalPrice: 1900,
    rentalPriceSquaremeterNet: 0,
    rentalPriceSquaremeter: 0,
    title: "W21_002",
    name: "21.002",
    rooms: 2.5,
    area: 67,
    virtualTourLink: "",
    balcony: 0,
    loggiaArea: 0,
    gardenSittingPlaceArea: 12,
    terraceArea: 0,
    basementArea: 10,
    parkingSpaceCost: 0,
    deposit: 0,
    reduitArea: 0,
    referenceNumber: "21.002",
  },
  {
    apartmentId: "W22_001",
    address: "Baarermatte, 6340 Baar",
    factsheet: "",
    incidentalCosts: 90,
    state: "frei",
    moveInDate: null,
    floor: "EG",
    floorNum: 0,
    priceUnit: "CHF",
    rentalPrice: 1900,
    rentalPriceSquaremeterNet: 0,
    rentalPriceSquaremeter: 0,
    title: "W22_001",
    name: "22.001",
    rooms: 2.5,
    area: 67,
    virtualTourLink: "",
    balcony: 0,
    loggiaArea: 0,
    gardenSittingPlaceArea: 12,
    terraceArea: 0,
    basementArea: 10,
    parkingSpaceCost: 0,
    deposit: 0,
    reduitArea: 0,
    referenceNumber: "22.001",
  },
  {
    apartmentId: "W22_002",
    address: "Baarermatte, 6340 Baar",
    factsheet: "",
    incidentalCosts: 90,
    state: "frei",
    moveInDate: null,
    floor: "EG",
    floorNum: 0,
    priceUnit: "CHF",
    rentalPrice: 1900,
    rentalPriceSquaremeterNet: 0,
    rentalPriceSquaremeter: 0,
    title: "W22_002",
    name: "22.002",
    rooms: 2.5,
    area: 67,
    virtualTourLink: "",
    balcony: 0,
    loggiaArea: 0,
    gardenSittingPlaceArea: 12,
    terraceArea: 0,
    basementArea: 10,
    parkingSpaceCost: 0,
    deposit: 0,
    reduitArea: 0,
    referenceNumber: "22.002",
  },
  {
    apartmentId: "W21_101",
    address: "Baarermatte, 6340 Baar",
    factsheet: "",
    incidentalCosts: 90,
    state: "frei",
    moveInDate: null,
    floor: "1.OG",
    floorNum: 1,
    priceUnit: "CHF",
    rentalPrice: 1900,
    rentalPriceSquaremeterNet: 0,
    rentalPriceSquaremeter: 0,
    title: "W21_101",
    name: "21.101",
    rooms: 2.5,
    area: 67,
    virtualTourLink: "",
    balcony: 10,
    loggiaArea: 0,
    gardenSittingPlaceArea: 0,
    terraceArea: 0,
    basementArea: 10,
    parkingSpaceCost: 0,
    deposit: 0,
    reduitArea: 0,
    referenceNumber: "21.101",
  },
  {
    apartmentId: "W21_102",
    address: "Baarermatte, 6340 Baar",
    factsheet: "",
    incidentalCosts: 90,
    state: "frei",
    moveInDate: null,
    floor: "1.OG",
    floorNum: 1,
    priceUnit: "CHF",
    rentalPrice: 1900,
    rentalPriceSquaremeterNet: 0,
    rentalPriceSquaremeter: 0,
    title: "W21_102",
    name: "21.102",
    rooms: 2.5,
    area: 67,
    virtualTourLink: "",
    balcony: 12,
    loggiaArea: 0,
    gardenSittingPlaceArea: 0,
    terraceArea: 0,
    basementArea: 10,
    parkingSpaceCost: 0,
    deposit: 0,
    reduitArea: 0,
    referenceNumber: "21.102",
  },
  {
    apartmentId: "W22_101",
    address: "Baarermatte, 6340 Baar",
    factsheet: "",
    incidentalCosts: 90,
    state: "frei",
    moveInDate: null,
    floor: "1.OG",
    floorNum: 1,
    priceUnit: "CHF",
    rentalPrice: 1900,
    rentalPriceSquaremeterNet: 0,
    rentalPriceSquaremeter: 0,
    title: "W22_101",
    name: "22.101",
    rooms: 2.5,
    area: 67,
    virtualTourLink: "",
    balcony: 12,
    loggiaArea: 0,
    gardenSittingPlaceArea: 0,
    terraceArea: 0,
    basementArea: 10,
    parkingSpaceCost: 0,
    deposit: 0,
    reduitArea: 0,
    referenceNumber: "22.101",
  },
  {
    apartmentId: "W22_102",
    address: "Baarermatte, 6340 Baar",
    factsheet: "",
    incidentalCosts: 90,
    state: "frei",
    moveInDate: null,
    floor: "1.OG",
    floorNum: 1,
    priceUnit: "CHF",
    rentalPrice: 1900,
    rentalPriceSquaremeterNet: 0,
    rentalPriceSquaremeter: 0,
    title: "W22_102",
    name: "22.102",
    rooms: 2.5,
    area: 67,
    virtualTourLink: "",
    balcony: 12,
    loggiaArea: 0,
    gardenSittingPlaceArea: 0,
    terraceArea: 0,
    basementArea: 10,
    parkingSpaceCost: 0,
    deposit: 0,
    reduitArea: 0,
    referenceNumber: "22.101",
  },
  {
    apartmentId: "W21_201",
    address: "Baarermatte, 6340 Baar",
    factsheet: "",
    incidentalCosts: 90,
    state: "frei",
    moveInDate: null,
    floor: "2.OG",
    floorNum: 2,
    priceUnit: "CHF",
    rentalPrice: 1900,
    rentalPriceSquaremeterNet: 0,
    rentalPriceSquaremeter: 0,
    title: "W21_201",
    name: "21.201",
    rooms: 2.5,
    area: 67,
    virtualTourLink: "",
    balcony: 12,
    loggiaArea: 0,
    gardenSittingPlaceArea: 0,
    terraceArea: 0,
    basementArea: 10,
    parkingSpaceCost: 0,
    deposit: 0,
    reduitArea: 0,
    referenceNumber: "21.201",
  },
  {
    apartmentId: "W21_202",
    address: "Baarermatte, 6340 Baar",
    factsheet: "",
    incidentalCosts: 90,
    state: "frei",
    moveInDate: null,
    floor: "2.OG",
    floorNum: 2,
    priceUnit: "CHF",
    rentalPrice: 1900,
    rentalPriceSquaremeterNet: 0,
    rentalPriceSquaremeter: 0,
    title: "W21_202",
    name: "21.202",
    rooms: 2.5,
    area: 67,
    virtualTourLink: "",
    balcony: 12,
    loggiaArea: 0,
    gardenSittingPlaceArea: 0,
    terraceArea: 0,
    basementArea: 10,
    parkingSpaceCost: 0,
    deposit: 0,
    reduitArea: 0,
    referenceNumber: "21.202",
  },
  {
    apartmentId: "W22_201",
    address: "Baarermatte, 6340 Baar",
    factsheet: "",
    incidentalCosts: 90,
    state: "frei",
    moveInDate: null,
    floor: "2.OG",
    floorNum: 2,
    priceUnit: "CHF",
    rentalPrice: 1900,
    rentalPriceSquaremeterNet: 0,
    rentalPriceSquaremeter: 0,
    title: "W22_201",
    name: "22.201",
    rooms: 2.5,
    area: 67,
    virtualTourLink: "",
    balcony: 12,
    loggiaArea: 0,
    gardenSittingPlaceArea: 0,
    terraceArea: 0,
    basementArea: 10,
    parkingSpaceCost: 0,
    deposit: 0,
    reduitArea: 0,
    referenceNumber: "22.201",
  },
  {
    apartmentId: "W22_202",
    address: "Baarermatte, 6340 Baar",
    factsheet: "",
    incidentalCosts: 90,
    state: "frei",
    moveInDate: null,
    floor: "2.OG",
    floorNum: 2,
    priceUnit: "CHF",
    rentalPrice: 1900,
    rentalPriceSquaremeterNet: 0,
    rentalPriceSquaremeter: 0,
    title: "W22_202",
    name: "22.202",
    rooms: 2.5,
    area: 67,
    virtualTourLink: "",
    balcony: 12,
    loggiaArea: 0,
    gardenSittingPlaceArea: 0,
    terraceArea: 0,
    basementArea: 10,
    parkingSpaceCost: 0,
    deposit: 0,
    reduitArea: 0,
    referenceNumber: "22.202",
  },
  {
    apartmentId: "W21_301",
    address: "Baarermatte, 6340 Baar",
    factsheet: "",
    incidentalCosts: 90,
    state: "frei",
    moveInDate: null,
    floor: "3.OG",
    floorNum: 3,
    priceUnit: "CHF",
    rentalPrice: 2100,
    rentalPriceSquaremeterNet: 0,
    rentalPriceSquaremeter: 0,
    title: "W21_301",
    name: "21.301",
    rooms: 3.5,
    area: 80,
    virtualTourLink: "",
    balcony: 12,
    loggiaArea: 0,
    gardenSittingPlaceArea: 0,
    terraceArea: 0,
    basementArea: 10,
    parkingSpaceCost: 0,
    deposit: 0,
    reduitArea: 0,
    referenceNumber: "21.301",
  },
  {
    apartmentId: "W21_302",
    address: "Baarermatte, 6340 Baar",
    factsheet: "",
    incidentalCosts: 90,
    state: "frei",
    moveInDate: null,
    floor: "3.OG",
    floorNum: 3,
    priceUnit: "CHF",
    rentalPrice: 2100,
    rentalPriceSquaremeterNet: 0,
    rentalPriceSquaremeter: 0,
    title: "W21_302",
    name: "21.302",
    rooms: 3.5,
    area: 80,
    virtualTourLink: "",
    balcony: 12,
    loggiaArea: 0,
    gardenSittingPlaceArea: 0,
    terraceArea: 0,
    basementArea: 10,
    parkingSpaceCost: 0,
    deposit: 0,
    reduitArea: 0,
    referenceNumber: "21.302",
  },
  {
    apartmentId: "W22_301",
    address: "Baarermatte, 6340 Baar",
    factsheet: "",
    incidentalCosts: 90,
    state: "frei",
    moveInDate: null,
    floor: "3.OG",
    floorNum: 3,
    priceUnit: "CHF",
    rentalPrice: 2100,
    rentalPriceSquaremeterNet: 0,
    rentalPriceSquaremeter: 0,
    title: "W22_301",
    name: "22.301",
    rooms: 3.5,
    area: 80,
    virtualTourLink: "",
    balcony: 12,
    loggiaArea: 0,
    gardenSittingPlaceArea: 0,
    terraceArea: 0,
    basementArea: 10,
    parkingSpaceCost: 0,
    deposit: 0,
    reduitArea: 0,
    referenceNumber: "22.301",
  },
  {
    apartmentId: "W22_302",
    address: "Baarermatte, 6340 Baar",
    factsheet: "",
    incidentalCosts: 90,
    state: "frei",
    moveInDate: null,
    floor: "3.OG",
    floorNum: 3,
    priceUnit: "CHF",
    rentalPrice: 2100,
    rentalPriceSquaremeterNet: 0,
    rentalPriceSquaremeter: 0,
    title: "W22_302",
    name: "22.302",
    rooms: 3.5,
    area: 80,
    virtualTourLink: "",
    balcony: 12,
    loggiaArea: 0,
    gardenSittingPlaceArea: 0,
    terraceArea: 0,
    basementArea: 10,
    parkingSpaceCost: 0,
    deposit: 0,
    reduitArea: 0,
    referenceNumber: "22.302",
  },
  {
    apartmentId: "W21_401",
    address: "Baarermatte, 6340 Baar",
    factsheet: "",
    incidentalCosts: 90,
    state: "frei",
    moveInDate: null,
    floor: "4.OG",
    floorNum: 4,
    priceUnit: "CHF",
    rentalPrice: 2200,
    rentalPriceSquaremeterNet: 0,
    rentalPriceSquaremeter: 0,
    title: "W21_401",
    name: "21.401",
    rooms: 3.5,
    area: 80,
    virtualTourLink: "",
    balcony: 12,
    loggiaArea: 0,
    gardenSittingPlaceArea: 0,
    terraceArea: 0,
    basementArea: 10,
    parkingSpaceCost: 0,
    deposit: 0,
    reduitArea: 0,
    referenceNumber: "21.401",
  },
  {
    apartmentId: "W21_402",
    address: "Baarermatte, 6340 Baar",
    factsheet: "",
    incidentalCosts: 90,
    state: "frei",
    moveInDate: null,
    floor: "4.OG",
    floorNum: 4,
    priceUnit: "CHF",
    rentalPrice: 2200,
    rentalPriceSquaremeterNet: 0,
    rentalPriceSquaremeter: 0,
    title: "W21_402",
    name: "21.402",
    rooms: 3.5,
    area: 80,
    virtualTourLink: "",
    balcony: 12,
    loggiaArea: 0,
    gardenSittingPlaceArea: 0,
    terraceArea: 0,
    basementArea: 10,
    parkingSpaceCost: 0,
    deposit: 0,
    reduitArea: 0,
    referenceNumber: "21.402",
  },
  {
    apartmentId: "W22_401",
    address: "Baarermatte, 6340 Baar",
    factsheet: "",
    incidentalCosts: 90,
    state: "frei",
    moveInDate: null,
    floor: "4.OG",
    floorNum: 4,
    priceUnit: "CHF",
    rentalPrice: 2200,
    rentalPriceSquaremeterNet: 0,
    rentalPriceSquaremeter: 0,
    title: "W22_401",
    name: "21.401",
    rooms: 3.5,
    area: 80,
    virtualTourLink: "",
    balcony: 12,
    loggiaArea: 0,
    gardenSittingPlaceArea: 0,
    terraceArea: 0,
    basementArea: 10,
    parkingSpaceCost: 0,
    deposit: 0,
    reduitArea: 0,
    referenceNumber: "21.401",
  },
  {
    apartmentId: "W22_402",
    address: "Baarermatte, 6340 Baar",
    factsheet: "",
    incidentalCosts: 90,
    state: "frei",
    moveInDate: null,
    floor: "4.OG",
    floorNum: 4,
    priceUnit: "CHF",
    rentalPrice: 2200,
    rentalPriceSquaremeterNet: 0,
    rentalPriceSquaremeter: 0,
    title: "W22_402",
    name: "22.402",
    rooms: 3.5,
    area: 80,
    virtualTourLink: "",
    balcony: 12,
    loggiaArea: 0,
    gardenSittingPlaceArea: 0,
    terraceArea: 0,
    basementArea: 10,
    parkingSpaceCost: 0,
    deposit: 0,
    reduitArea: 0,
    referenceNumber: "22.402",
  },
  {
    apartmentId: "W21_501",
    address: "Baarermatte, 6340 Baar",
    factsheet: "",
    incidentalCosts: 90,
    state: "frei",
    moveInDate: null,
    floor: "5.OG",
    floorNum: 5,
    priceUnit: "CHF",
    rentalPrice: 2500,
    rentalPriceSquaremeterNet: 0,
    rentalPriceSquaremeter: 0,
    title: "W21_501",
    name: "21.501",
    rooms: 4.5,
    area: 110,
    virtualTourLink: "",
    balcony: 12,
    loggiaArea: 0,
    gardenSittingPlaceArea: 0,
    terraceArea: 0,
    basementArea: 10,
    parkingSpaceCost: 0,
    deposit: 0,
    reduitArea: 0,
    referenceNumber: "21.501",
  },
  {
    apartmentId: "W21_502",
    address: "Baarermatte, 6340 Baar",
    factsheet: "",
    incidentalCosts: 90,
    state: "frei",
    moveInDate: null,
    floor: "5.OG",
    floorNum: 5,
    priceUnit: "CHF",
    rentalPrice: 2500,
    rentalPriceSquaremeterNet: 0,
    rentalPriceSquaremeter: 0,
    title: "W21_502",
    name: "21.502",
    rooms: 4.5,
    area: 110,
    virtualTourLink: "",
    balcony: 12,
    loggiaArea: 0,
    gardenSittingPlaceArea: 0,
    terraceArea: 0,
    basementArea: 10,
    parkingSpaceCost: 0,
    deposit: 0,
    reduitArea: 0,
    referenceNumber: "21.502",
  },
  {
    apartmentId: "W22_501",
    address: "Baarermatte, 6340 Baar",
    factsheet: "",
    incidentalCosts: 90,
    state: "frei",
    moveInDate: null,
    floor: "5.OG",
    floorNum: 5,
    priceUnit: "CHF",
    rentalPrice: 2500,
    rentalPriceSquaremeterNet: 0,
    rentalPriceSquaremeter: 0,
    title: "W22_501",
    name: "22.501",
    rooms: 4.5,
    area: 110,
    virtualTourLink: "",
    balcony: 12,
    loggiaArea: 0,
    gardenSittingPlaceArea: 0,
    terraceArea: 0,
    basementArea: 10,
    parkingSpaceCost: 0,
    deposit: 0,
    reduitArea: 0,
    referenceNumber: "22.501",
  },
  {
    apartmentId: "W22_502",
    address: "Baarermatte, 6340 Baar",
    factsheet: "",
    incidentalCosts: 90,
    state: "frei",
    moveInDate: null,
    floor: "5.OG",
    floorNum: 5,
    priceUnit: "CHF",
    rentalPrice: 2500,
    rentalPriceSquaremeterNet: 0,
    rentalPriceSquaremeter: 0,
    title: "W22_502",
    name: "22.502",
    rooms: 4.5,
    area: 110,
    virtualTourLink: "",
    balcony: 12,
    loggiaArea: 0,
    gardenSittingPlaceArea: 0,
    terraceArea: 0,
    basementArea: 10,
    parkingSpaceCost: 0,
    deposit: 0,
    reduitArea: 0,
    referenceNumber: "22.502",
  },

  {
    apartmentId: "W31_001",
    address: "Baarermatte, 6340 Baar",
    factsheet: "",
    incidentalCosts: 90,
    state: "frei",
    moveInDate: null,
    floor: "EG",
    floorNum: 0,
    priceUnit: "CHF",
    rentalPrice: 2000,
    rentalPriceSquaremeterNet: 0,
    rentalPriceSquaremeter: 0,
    title: "W31_001",
    name: "31.001",
    rooms: 2.5,
    area: 60,
    virtualTourLink: "",
    balcony: 0,
    loggiaArea: 0,
    gardenSittingPlaceArea: 12,
    terraceArea: 0,
    basementArea: 10,
    parkingSpaceCost: 0,
    deposit: 0,
    reduitArea: 0,
    referenceNumber: "31.001",
  },
  {
    apartmentId: "W31_002",
    address: "Baarermatte, 6340 Baar",
    factsheet: "",
    incidentalCosts: 90,
    state: "frei",
    moveInDate: null,
    floor: "EG",
    floorNum: 0,
    priceUnit: "CHF",
    rentalPrice: 2000,
    rentalPriceSquaremeterNet: 0,
    rentalPriceSquaremeter: 0,
    title: "W31_002",
    name: "31.002",
    rooms: 2.5,
    area: 60,
    virtualTourLink: "",
    balcony: 0,
    loggiaArea: 0,
    gardenSittingPlaceArea: 12,
    terraceArea: 0,
    basementArea: 10,
    parkingSpaceCost: 0,
    deposit: 0,
    reduitArea: 0,
    referenceNumber: "31.002",
  },
  {
    apartmentId: "W32_001",
    address: "Baarermatte, 6340 Baar",
    factsheet: "",
    incidentalCosts: 90,
    state: "frei",
    moveInDate: null,
    floor: "EG",
    floorNum: 0,
    priceUnit: "CHF",
    rentalPrice: 2000,
    rentalPriceSquaremeterNet: 0,
    rentalPriceSquaremeter: 0,
    title: "W32_001",
    name: "32.001",
    rooms: 2.5,
    area: 60,
    virtualTourLink: "",
    balcony: 0,
    loggiaArea: 0,
    gardenSittingPlaceArea: 12,
    terraceArea: 0,
    basementArea: 10,
    parkingSpaceCost: 0,
    deposit: 0,
    reduitArea: 0,
    referenceNumber: "32.001",
  },
  {
    apartmentId: "W32_002",
    address: "Baarermatte, 6340 Baar",
    factsheet: "",
    incidentalCosts: 90,
    state: "frei",
    moveInDate: null,
    floor: "EG",
    floorNum: 0,
    priceUnit: "CHF",
    rentalPrice: 2000,
    rentalPriceSquaremeterNet: 0,
    rentalPriceSquaremeter: 0,
    title: "W32_002",
    name: "32.002",
    rooms: 2.5,
    area: 60,
    virtualTourLink: "",
    balcony: 0,
    loggiaArea: 0,
    gardenSittingPlaceArea: 12,
    terraceArea: 0,
    basementArea: 10,
    parkingSpaceCost: 0,
    deposit: 0,
    reduitArea: 0,
    referenceNumber: "32.002",
  },
  {
    apartmentId: "W31_101",
    address: "Baarermatte, 6340 Baar",
    factsheet: "",
    incidentalCosts: 90,
    state: "frei",
    moveInDate: null,
    floor: "1.OG",
    floorNum: 1,
    priceUnit: "CHF",
    rentalPrice: 2100,
    rentalPriceSquaremeterNet: 0,
    rentalPriceSquaremeter: 0,
    title: "W31_101",
    name: "31.101",
    rooms: 2.5,
    area: 60,
    virtualTourLink: "",
    balcony: 12,
    loggiaArea: 0,
    gardenSittingPlaceArea: 0,
    terraceArea: 0,
    basementArea: 10,
    parkingSpaceCost: 0,
    deposit: 0,
    reduitArea: 0,
    referenceNumber: "31.101",
  },
  {
    apartmentId: "W31_102",
    address: "Baarermatte, 6340 Baar",
    factsheet: "",
    incidentalCosts: 90,
    state: "frei",
    moveInDate: null,
    floor: "1.OG",
    floorNum: 1,
    priceUnit: "CHF",
    rentalPrice: 2200,
    rentalPriceSquaremeterNet: 0,
    rentalPriceSquaremeter: 0,
    title: "W31_102",
    name: "31.102",
    rooms: 2.5,
    area: 60,
    virtualTourLink: "",
    balcony: 0,
    loggiaArea: 0,
    gardenSittingPlaceArea: 0,
    terraceArea: 0,
    basementArea: 10,
    parkingSpaceCost: 0,
    deposit: 0,
    reduitArea: 0,
    referenceNumber: "31.102",
  },
  {
    apartmentId: "W32_101",
    address: "Baarermatte, 6340 Baar",
    factsheet: "",
    incidentalCosts: 90,
    state: "frei",
    moveInDate: null,
    floor: "1.OG",
    floorNum: 1,
    priceUnit: "CHF",
    rentalPrice: 2200,
    rentalPriceSquaremeterNet: 0,
    rentalPriceSquaremeter: 0,
    title: "W32_101",
    name: "32.101",
    rooms: 2.5,
    area: 60,
    virtualTourLink: "",
    balcony: 12,
    loggiaArea: 0,
    gardenSittingPlaceArea: 0,
    terraceArea: 0,
    basementArea: 10,
    parkingSpaceCost: 0,
    deposit: 0,
    reduitArea: 0,
    referenceNumber: "32.101",
  },
  {
    apartmentId: "W32_102",
    address: "Baarermatte, 6340 Baar",
    factsheet: "",
    incidentalCosts: 90,
    state: "frei",
    moveInDate: null,
    floor: "1.OG",
    floorNum: 1,
    priceUnit: "CHF",
    rentalPrice: 2200,
    rentalPriceSquaremeterNet: 0,
    rentalPriceSquaremeter: 0,
    title: "W32_102",
    name: "32.102",
    rooms: 2.5,
    area: 60,
    virtualTourLink: "",
    balcony: 12,
    loggiaArea: 0,
    gardenSittingPlaceArea: 0,
    terraceArea: 0,
    basementArea: 10,
    parkingSpaceCost: 0,
    deposit: 0,
    reduitArea: 0,
    referenceNumber: "32.102",
  },
  {
    apartmentId: "W31_201",
    address: "Baarermatte, 6340 Baar",
    factsheet: "",
    incidentalCosts: 90,
    state: "frei",
    moveInDate: null,
    floor: "2.OG",
    floorNum: 2,
    priceUnit: "CHF",
    rentalPrice: 2400,
    rentalPriceSquaremeterNet: 0,
    rentalPriceSquaremeter: 0,
    title: "W31_201",
    name: "31.201",
    rooms: 3.5,
    area: 80,
    virtualTourLink: "",
    balcony: 12,
    loggiaArea: 0,
    gardenSittingPlaceArea: 0,
    terraceArea: 0,
    basementArea: 10,
    parkingSpaceCost: 0,
    deposit: 0,
    reduitArea: 0,
    referenceNumber: "31.201",
  },
  {
    apartmentId: "W31_202",
    address: "Baarermatte, 6340 Baar",
    factsheet: "",
    incidentalCosts: 90,
    state: "frei",
    moveInDate: null,
    floor: "2.OG",
    floorNum: 2,
    priceUnit: "CHF",
    rentalPrice: 2400,
    rentalPriceSquaremeterNet: 0,
    rentalPriceSquaremeter: 0,
    title: "W31_202",
    name: "31.202",
    rooms: 3.5,
    area: 80,
    virtualTourLink: "",
    balcony: 12,
    loggiaArea: 0,
    gardenSittingPlaceArea: 0,
    terraceArea: 0,
    basementArea: 10,
    parkingSpaceCost: 0,
    deposit: 0,
    reduitArea: 0,
    referenceNumber: "31.202",
  },
  {
    apartmentId: "W32_201",
    address: "Baarermatte, 6340 Baar",
    factsheet: "",
    incidentalCosts: 90,
    state: "frei",
    moveInDate: null,
    floor: "2.OG",
    floorNum: 2,
    priceUnit: "CHF",
    rentalPrice: 2400,
    rentalPriceSquaremeterNet: 0,
    rentalPriceSquaremeter: 0,
    title: "W32_201",
    name: "31.201",
    rooms: 3.5,
    area: 80,
    virtualTourLink: "",
    balcony: 12,
    loggiaArea: 0,
    gardenSittingPlaceArea: 0,
    terraceArea: 0,
    basementArea: 10,
    parkingSpaceCost: 0,
    deposit: 0,
    reduitArea: 0,
    referenceNumber: "31.201",
  },
  {
    apartmentId: "W32_202",
    address: "Baarermatte, 6340 Baar",
    factsheet: "",
    incidentalCosts: 90,
    state: "frei",
    moveInDate: null,
    floor: "2.OG",
    floorNum: 2,
    priceUnit: "CHF",
    rentalPrice: 2400,
    rentalPriceSquaremeterNet: 0,
    rentalPriceSquaremeter: 0,
    title: "W32_202",
    name: "32.202",
    rooms: 3.5,
    area: 80,
    virtualTourLink: "",
    balcony: 12,
    loggiaArea: 0,
    gardenSittingPlaceArea: 0,
    terraceArea: 0,
    basementArea: 10,
    parkingSpaceCost: 0,
    deposit: 0,
    reduitArea: 0,
    referenceNumber: "32.202",
  },
  {
    apartmentId: "W31_301",
    address: "Baarermatte, 6340 Baar",
    factsheet: "",
    incidentalCosts: 90,
    state: "frei",
    moveInDate: null,
    floor: "3.OG",
    floorNum: 3,
    priceUnit: "CHF",
    rentalPrice: 2600,
    rentalPriceSquaremeterNet: 0,
    rentalPriceSquaremeter: 0,
    title: "W31_301",
    name: "31.301",
    rooms: 3.5,
    area: 80,
    virtualTourLink: "",
    balcony: 12,
    loggiaArea: 0,
    gardenSittingPlaceArea: 0,
    terraceArea: 0,
    basementArea: 10,
    parkingSpaceCost: 0,
    deposit: 0,
    reduitArea: 0,
    referenceNumber: "31.301",
  },
  {
    apartmentId: "W31_302",
    address: "Baarermatte, 6340 Baar",
    factsheet: "",
    incidentalCosts: 90,
    state: "frei",
    moveInDate: null,
    floor: "3.OG",
    floorNum: 3,
    priceUnit: "CHF",
    rentalPrice: 2600,
    rentalPriceSquaremeterNet: 0,
    rentalPriceSquaremeter: 0,
    title: "W31_302",
    name: "31.302",
    rooms: 3.5,
    area: 80,
    virtualTourLink: "",
    balcony: 12,
    loggiaArea: 0,
    gardenSittingPlaceArea: 0,
    terraceArea: 0,
    basementArea: 10,
    parkingSpaceCost: 0,
    deposit: 0,
    reduitArea: 0,
    referenceNumber: "31.302",
  },
  {
    apartmentId: "W32_301",
    address: "Baarermatte, 6340 Baar",
    factsheet: "",
    incidentalCosts: 90,
    state: "frei",
    moveInDate: null,
    floor: "3.OG",
    floorNum: 3,
    priceUnit: "CHF",
    rentalPrice: 2600,
    rentalPriceSquaremeterNet: 0,
    rentalPriceSquaremeter: 0,
    title: "W32_301",
    name: "32.301",
    rooms: 3.5,
    area: 80,
    virtualTourLink: "",
    balcony: 12,
    loggiaArea: 0,
    gardenSittingPlaceArea: 0,
    terraceArea: 0,
    basementArea: 10,
    parkingSpaceCost: 0,
    deposit: 0,
    reduitArea: 0,
    referenceNumber: "32.301",
  },
  {
    apartmentId: "W32_302",
    address: "Baarermatte, 6340 Baar",
    factsheet: "",
    incidentalCosts: 90,
    state: "frei",
    moveInDate: null,
    floor: "3.OG",
    floorNum: 3,
    priceUnit: "CHF",
    rentalPrice: 2600,
    rentalPriceSquaremeterNet: 0,
    rentalPriceSquaremeter: 0,
    title: "W32_302",
    name: "32.302",
    rooms: 3.5,
    area: 80,
    virtualTourLink: "",
    balcony: 12,
    loggiaArea: 0,
    gardenSittingPlaceArea: 0,
    terraceArea: 0,
    basementArea: 10,
    parkingSpaceCost: 0,
    deposit: 0,
    reduitArea: 0,
    referenceNumber: "32.302",
  },
  {
    apartmentId: "W31_401",
    address: "Baarermatte, 6340 Baar",
    factsheet: "",
    incidentalCosts: 90,
    state: "frei",
    moveInDate: null,
    floor: "4.OG",
    floorNum: 4,
    priceUnit: "CHF",
    rentalPrice: 2700,
    rentalPriceSquaremeterNet: 0,
    rentalPriceSquaremeter: 0,
    title: "W31_401",
    name: "31.401",
    rooms: 4.5,
    area: 80,
    virtualTourLink: "",
    balcony: 12,
    loggiaArea: 0,
    gardenSittingPlaceArea: 0,
    terraceArea: 0,
    basementArea: 10,
    parkingSpaceCost: 0,
    deposit: 0,
    reduitArea: 0,
    referenceNumber: "31.401",
  },
  {
    apartmentId: "W31_402",
    address: "Baarermatte, 6340 Baar",
    factsheet: "",
    incidentalCosts: 90,
    state: "frei",
    moveInDate: null,
    floor: "4.OG",
    floorNum: 4,
    priceUnit: "CHF",
    rentalPrice: 2700,
    rentalPriceSquaremeterNet: 0,
    rentalPriceSquaremeter: 0,
    title: "W31_402",
    name: "31.402",
    rooms: 4.5,
    area: 80,
    virtualTourLink: "",
    balcony: 12,
    loggiaArea: 0,
    gardenSittingPlaceArea: 0,
    terraceArea: 0,
    basementArea: 10,
    parkingSpaceCost: 0,
    deposit: 0,
    reduitArea: 0,
    referenceNumber: "31.402",
  },
  {
    apartmentId: "W32_401",
    address: "Baarermatte, 6340 Baar",
    factsheet: "",
    incidentalCosts: 90,
    state: "frei",
    moveInDate: null,
    floor: "4.OG",
    floorNum: 4,
    priceUnit: "CHF",
    rentalPrice: 2700,
    rentalPriceSquaremeterNet: 0,
    rentalPriceSquaremeter: 0,
    title: "W32_401",
    name: "32.401",
    rooms: 4.5,
    area: 80,
    virtualTourLink: "",
    balcony: 12,
    loggiaArea: 0,
    gardenSittingPlaceArea: 0,
    terraceArea: 0,
    basementArea: 10,
    parkingSpaceCost: 0,
    deposit: 0,
    reduitArea: 0,
    referenceNumber: "32.401",
  },
  {
    apartmentId: "W32_402",
    address: "Baarermatte, 6340 Baar",
    factsheet: "",
    incidentalCosts: 90,
    state: "frei",
    moveInDate: null,
    floor: "4.OG",
    floorNum: 4,
    priceUnit: "CHF",
    rentalPrice: 2700,
    rentalPriceSquaremeterNet: 0,
    rentalPriceSquaremeter: 0,
    title: "W32_402",
    name: "32.402",
    rooms: 4.5,
    area: 80,
    virtualTourLink: "",
    balcony: 12,
    loggiaArea: 0,
    gardenSittingPlaceArea: 0,
    terraceArea: 0,
    basementArea: 10,
    parkingSpaceCost: 0,
    deposit: 0,
    reduitArea: 0,
    referenceNumber: "32.402",
  },
  {
    apartmentId: "W31_501",
    address: "Baarermatte, 6340 Baar",
    factsheet: "",
    incidentalCosts: 100,
    state: "frei",
    moveInDate: null,
    floor: "5.OG",
    floorNum: 5,
    priceUnit: "CHF",
    rentalPrice: 2800,
    rentalPriceSquaremeterNet: 0,
    rentalPriceSquaremeter: 0,
    title: "W31_501",
    name: "31.501",
    rooms: 4.5,
    area: 100,
    virtualTourLink: "",
    balcony: 12,
    loggiaArea: 0,
    gardenSittingPlaceArea: 0,
    terraceArea: 0,
    basementArea: 10,
    parkingSpaceCost: 0,
    deposit: 0,
    reduitArea: 0,
    referenceNumber: "31.501",
  },
  {
    apartmentId: "W31_502",
    address: "Baarermatte, 6340 Baar",
    factsheet: "",
    incidentalCosts: 100,
    state: "frei",
    moveInDate: null,
    floor: "5.OG",
    floorNum: 5,
    priceUnit: "CHF",
    rentalPrice: 2800,
    rentalPriceSquaremeterNet: 0,
    rentalPriceSquaremeter: 0,
    title: "W31_502",
    name: "31.502",
    rooms: 4.5,
    area: 100,
    virtualTourLink: "",
    balcony: 12,
    loggiaArea: 0,
    gardenSittingPlaceArea: 0,
    terraceArea: 0,
    basementArea: 10,
    parkingSpaceCost: 0,
    deposit: 0,
    reduitArea: 0,
    referenceNumber: "31.502",
  },
  {
    apartmentId: "W32_501",
    address: "Baarermatte, 6340 Baar",
    factsheet: "",
    incidentalCosts: 100,
    state: "frei",
    moveInDate: null,
    floor: "5.OG",
    floorNum: 5,
    priceUnit: "CHF",
    rentalPrice: 2800,
    rentalPriceSquaremeterNet: 0,
    rentalPriceSquaremeter: 0,
    title: "W32_501",
    name: "31.501",
    rooms: 4.5,
    area: 100,
    virtualTourLink: "",
    balcony: 12,
    loggiaArea: 0,
    gardenSittingPlaceArea: 0,
    terraceArea: 0,
    basementArea: 10,
    parkingSpaceCost: 0,
    deposit: 0,
    reduitArea: 0,
    referenceNumber: "31.501",
  },
  {
    apartmentId: "W32_502",
    address: "Baarermatte, 6340 Baar",
    factsheet: "",
    incidentalCosts: 100,
    state: "frei",
    moveInDate: null,
    floor: "5.OG",
    floorNum: 5,
    priceUnit: "CHF",
    rentalPrice: 2800,
    rentalPriceSquaremeterNet: 0,
    rentalPriceSquaremeter: 0,
    title: "W32_502",
    name: "31.502",
    rooms: 4.5,
    area: 100,
    virtualTourLink: "",
    balcony: 12,
    loggiaArea: 0,
    gardenSittingPlaceArea: 0,
    terraceArea: 0,
    basementArea: 10,
    parkingSpaceCost: 0,
    deposit: 0,
    reduitArea: 0,
    referenceNumber: "31.502",
  },
  {
    apartmentId: "W41_001",
    address: "Baarermatte, 6340 Baar",
    factsheet: "",
    incidentalCosts: 90,
    state: "frei",
    moveInDate: null,
    floor: "EG",
    floorNum: 0,
    priceUnit: "CHF",
    rentalPrice: 2000,
    rentalPriceSquaremeterNet: 0,
    rentalPriceSquaremeter: 0,
    title: "W41_001",
    name: "41.001",
    rooms: 2.5,
    area: 60,
    virtualTourLink: "",
    balcony: 0,
    loggiaArea: 0,
    gardenSittingPlaceArea: 12,
    terraceArea: 0,
    basementArea: 10,
    parkingSpaceCost: 0,
    deposit: 0,
    reduitArea: 0,
    referenceNumber: "41.001",
  },
  {
    apartmentId: "W41_002",
    address: "Baarermatte, 6340 Baar",
    factsheet: "",
    incidentalCosts: 90,
    state: "frei",
    moveInDate: null,
    floor: "EG",
    floorNum: 0,
    priceUnit: "CHF",
    rentalPrice: 2000,
    rentalPriceSquaremeterNet: 0,
    rentalPriceSquaremeter: 0,
    title: "W41_002",
    name: "41.002",
    rooms: 2.5,
    area: 60,
    virtualTourLink: "",
    balcony: 0,
    loggiaArea: 0,
    gardenSittingPlaceArea: 12,
    terraceArea: 0,
    basementArea: 10,
    parkingSpaceCost: 0,
    deposit: 0,
    reduitArea: 0,
    referenceNumber: "41.002",
  },
  {
    apartmentId: "W42_001",
    address: "Baarermatte, 6340 Baar",
    factsheet: "",
    incidentalCosts: 90,
    state: "frei",
    moveInDate: null,
    floor: "EG",
    floorNum: 0,
    priceUnit: "CHF",
    rentalPrice: 2000,
    rentalPriceSquaremeterNet: 0,
    rentalPriceSquaremeter: 0,
    title: "W42_001",
    name: "42.001",
    rooms: 2.5,
    area: 60,
    virtualTourLink: "",
    balcony: 0,
    loggiaArea: 0,
    gardenSittingPlaceArea: 12,
    terraceArea: 0,
    basementArea: 10,
    parkingSpaceCost: 0,
    deposit: 0,
    reduitArea: 0,
    referenceNumber: "42.001",
  },
  {
    apartmentId: "W42_002",
    address: "Baarermatte, 6340 Baar",
    factsheet: "",
    incidentalCosts: 90,
    state: "frei",
    moveInDate: null,
    floor: "EG",
    floorNum: 0,
    priceUnit: "CHF",
    rentalPrice: 2000,
    rentalPriceSquaremeterNet: 0,
    rentalPriceSquaremeter: 0,
    title: "W42_002",
    name: "42.002",
    rooms: 2.5,
    area: 60,
    virtualTourLink: "",
    balcony: 0,
    loggiaArea: 0,
    gardenSittingPlaceArea: 12,
    terraceArea: 0,
    basementArea: 10,
    parkingSpaceCost: 0,
    deposit: 0,
    reduitArea: 0,
    referenceNumber: "42.002",
  },
  {
    apartmentId: "W43_001",
    address: "Baarermatte, 6340 Baar",
    factsheet: "",
    incidentalCosts: 90,
    state: "frei",
    moveInDate: null,
    floor: "EG",
    floorNum: 0,
    priceUnit: "CHF",
    rentalPrice: 2000,
    rentalPriceSquaremeterNet: 0,
    rentalPriceSquaremeter: 0,
    title: "W43_001",
    name: "43.001",
    rooms: 2.5,
    area: 60,
    virtualTourLink: "",
    balcony: 0,
    loggiaArea: 0,
    gardenSittingPlaceArea: 12,
    terraceArea: 0,
    basementArea: 10,
    parkingSpaceCost: 0,
    deposit: 0,
    reduitArea: 0,
    referenceNumber: "43.001",
  },
  {
    apartmentId: "W43_002",
    address: "Baarermatte, 6340 Baar",
    factsheet: "",
    incidentalCosts: 90,
    state: "frei",
    moveInDate: null,
    floor: "EG",
    floorNum: 0,
    priceUnit: "CHF",
    rentalPrice: 2000,
    rentalPriceSquaremeterNet: 0,
    rentalPriceSquaremeter: 0,
    title: "W43_002",
    name: "43.002",
    rooms: 2.5,
    area: 60,
    virtualTourLink: "",
    balcony: 0,
    loggiaArea: 0,
    gardenSittingPlaceArea: 12,
    terraceArea: 0,
    basementArea: 10,
    parkingSpaceCost: 0,
    deposit: 0,
    reduitArea: 0,
    referenceNumber: "43.002",
  },
  {
    apartmentId: "W41_101",
    address: "Baarermatte, 6340 Baar",
    factsheet: "",
    incidentalCosts: 90,
    state: "frei",
    moveInDate: null,
    floor: "1.OG",
    floorNum: 1,
    priceUnit: "CHF",
    rentalPrice: 2100,
    rentalPriceSquaremeterNet: 0,
    rentalPriceSquaremeter: 0,
    title: "W41_101",
    name: "41.101",
    rooms: 2.5,
    area: 80,
    virtualTourLink: "",
    balcony: 12,
    loggiaArea: 0,
    gardenSittingPlaceArea: 0,
    terraceArea: 0,
    basementArea: 10,
    parkingSpaceCost: 0,
    deposit: 0,
    reduitArea: 0,
    referenceNumber: "41.101",
  },
  {
    apartmentId: "W41_102",
    address: "Baarermatte, 6340 Baar",
    factsheet: "",
    incidentalCosts: 90,
    state: "frei",
    moveInDate: null,
    floor: "1.OG",
    floorNum: 1,
    priceUnit: "CHF",
    rentalPrice: 2100,
    rentalPriceSquaremeterNet: 0,
    rentalPriceSquaremeter: 0,
    title: "W41_102",
    name: "41.102",
    rooms: 2.5,
    area: 80,
    virtualTourLink: "",
    balcony: 12,
    loggiaArea: 0,
    gardenSittingPlaceArea: 0,
    terraceArea: 0,
    basementArea: 10,
    parkingSpaceCost: 0,
    deposit: 0,
    reduitArea: 0,
    referenceNumber: "41.102",
  },
  {
    apartmentId: "W42_101",
    address: "Baarermatte, 6340 Baar",
    factsheet: "",
    incidentalCosts: 90,
    state: "frei",
    moveInDate: null,
    floor: "1.OG",
    floorNum: 1,
    priceUnit: "CHF",
    rentalPrice: 2100,
    rentalPriceSquaremeterNet: 0,
    rentalPriceSquaremeter: 0,
    title: "W42_101",
    name: "42.101",
    rooms: 2.5,
    area: 80,
    virtualTourLink: "",
    balcony: 12,
    loggiaArea: 0,
    gardenSittingPlaceArea: 0,
    terraceArea: 0,
    basementArea: 10,
    parkingSpaceCost: 0,
    deposit: 0,
    reduitArea: 0,
    referenceNumber: "42.101",
  },
  {
    apartmentId: "W42_102",
    address: "Baarermatte, 6340 Baar",
    factsheet: "",
    incidentalCosts: 90,
    state: "frei",
    moveInDate: null,
    floor: "1.OG",
    floorNum: 1,
    priceUnit: "CHF",
    rentalPrice: 2100,
    rentalPriceSquaremeterNet: 0,
    rentalPriceSquaremeter: 0,
    title: "W42_102",
    name: "42.102",
    rooms: 2.5,
    area: 80,
    virtualTourLink: "",
    balcony: 12,
    loggiaArea: 0,
    gardenSittingPlaceArea: 0,
    terraceArea: 0,
    basementArea: 10,
    parkingSpaceCost: 0,
    deposit: 0,
    reduitArea: 0,
    referenceNumber: "42.102",
  },
  {
    apartmentId: "W43_101",
    address: "Baarermatte, 6340 Baar",
    factsheet: "",
    incidentalCosts: 90,
    state: "frei",
    moveInDate: null,
    floor: "1.OG",
    floorNum: 1,
    priceUnit: "CHF",
    rentalPrice: 2100,
    rentalPriceSquaremeterNet: 0,
    rentalPriceSquaremeter: 0,
    title: "W43_101",
    name: "43.101",
    rooms: 2.5,
    area: 80,
    virtualTourLink: "",
    balcony: 12,
    loggiaArea: 0,
    gardenSittingPlaceArea: 0,
    terraceArea: 0,
    basementArea: 10,
    parkingSpaceCost: 0,
    deposit: 0,
    reduitArea: 0,
    referenceNumber: "42.101",
  },
  {
    apartmentId: "W43_102",
    address: "Baarermatte, 6340 Baar",
    factsheet: "",
    incidentalCosts: 90,
    state: "frei",
    moveInDate: null,
    floor: "1.OG",
    floorNum: 1,
    priceUnit: "CHF",
    rentalPrice: 2100,
    rentalPriceSquaremeterNet: 0,
    rentalPriceSquaremeter: 0,
    title: "W43_102",
    name: "43.102",
    rooms: 2.5,
    area: 80,
    virtualTourLink: "",
    balcony: 12,
    loggiaArea: 0,
    gardenSittingPlaceArea: 0,
    terraceArea: 0,
    basementArea: 10,
    parkingSpaceCost: 0,
    deposit: 0,
    reduitArea: 0,
    referenceNumber: "42.102",
  },
  {
    apartmentId: "W41_201",
    address: "Baarermatte, 6340 Baar",
    factsheet: "",
    incidentalCosts: 90,
    state: "frei",
    moveInDate: null,
    floor: "2.OG",
    floorNum: 2,
    priceUnit: "CHF",
    rentalPrice: 2100,
    rentalPriceSquaremeterNet: 0,
    rentalPriceSquaremeter: 0,
    title: "W41_201",
    name: "43.201",
    rooms: 3.5,
    area: 90,
    virtualTourLink: "",
    balcony: 12,
    loggiaArea: 0,
    gardenSittingPlaceArea: 0,
    terraceArea: 0,
    basementArea: 10,
    parkingSpaceCost: 0,
    deposit: 0,
    reduitArea: 0,
    referenceNumber: "43.201",
  },
  {
    apartmentId: "W41_202",
    address: "Baarermatte, 6340 Baar",
    factsheet: "",
    incidentalCosts: 90,
    state: "frei",
    moveInDate: null,
    floor: "2.OG",
    floorNum: 2,
    priceUnit: "CHF",
    rentalPrice: 2100,
    rentalPriceSquaremeterNet: 0,
    rentalPriceSquaremeter: 0,
    title: "W41_202",
    name: "43.202",
    rooms: 3.5,
    area: 90,
    virtualTourLink: "",
    balcony: 12,
    loggiaArea: 0,
    gardenSittingPlaceArea: 0,
    terraceArea: 0,
    basementArea: 10,
    parkingSpaceCost: 0,
    deposit: 0,
    reduitArea: 0,
    referenceNumber: "43.202",
  },
  {
    apartmentId: "W42_201",
    address: "Baarermatte, 6340 Baar",
    factsheet: "",
    incidentalCosts: 90,
    state: "frei",
    moveInDate: null,
    floor: "2.OG",
    floorNum: 2,
    priceUnit: "CHF",
    rentalPrice: 2100,
    rentalPriceSquaremeterNet: 0,
    rentalPriceSquaremeter: 0,
    title: "W42_201",
    name: "43.201",
    rooms: 3.5,
    area: 90,
    virtualTourLink: "",
    balcony: 12,
    loggiaArea: 0,
    gardenSittingPlaceArea: 0,
    terraceArea: 0,
    basementArea: 10,
    parkingSpaceCost: 0,
    deposit: 0,
    reduitArea: 0,
    referenceNumber: "43.201",
  },
  {
    apartmentId: "W42_202",
    address: "Baarermatte, 6340 Baar",
    factsheet: "",
    incidentalCosts: 90,
    state: "frei",
    moveInDate: null,
    floor: "2.OG",
    floorNum: 2,
    priceUnit: "CHF",
    rentalPrice: 2100,
    rentalPriceSquaremeterNet: 0,
    rentalPriceSquaremeter: 0,
    title: "W42_202",
    name: "42.202",
    rooms: 3.5,
    area: 90,
    virtualTourLink: "",
    balcony: 12,
    loggiaArea: 0,
    gardenSittingPlaceArea: 0,
    terraceArea: 0,
    basementArea: 10,
    parkingSpaceCost: 0,
    deposit: 0,
    reduitArea: 0,
    referenceNumber: "42.202",
  },
  {
    apartmentId: "W43_201",
    address: "Baarermatte, 6340 Baar",
    factsheet: "",
    incidentalCosts: 90,
    state: "frei",
    moveInDate: null,
    floor: "2.OG",
    floorNum: 2,
    priceUnit: "CHF",
    rentalPrice: 2100,
    rentalPriceSquaremeterNet: 0,
    rentalPriceSquaremeter: 0,
    title: "W43_201",
    name: "43.201",
    rooms: 3.5,
    area: 90,
    virtualTourLink: "",
    balcony: 12,
    loggiaArea: 0,
    gardenSittingPlaceArea: 0,
    terraceArea: 0,
    basementArea: 10,
    parkingSpaceCost: 0,
    deposit: 0,
    reduitArea: 0,
    referenceNumber: "43.201",
  },
  {
    apartmentId: "W43_202",
    address: "Baarermatte, 6340 Baar",
    factsheet: "",
    incidentalCosts: 90,
    state: "frei",
    moveInDate: null,
    floor: "2.OG",
    floorNum: 2,
    priceUnit: "CHF",
    rentalPrice: 2100,
    rentalPriceSquaremeterNet: 0,
    rentalPriceSquaremeter: 0,
    title: "W43_202",
    name: "43.202",
    rooms: 3.5,
    area: 90,
    virtualTourLink: "",
    balcony: 12,
    loggiaArea: 0,
    gardenSittingPlaceArea: 0,
    terraceArea: 0,
    basementArea: 10,
    parkingSpaceCost: 0,
    deposit: 0,
    reduitArea: 0,
    referenceNumber: "43.202",
  },
  {
    apartmentId: "W41_301",
    address: "Baarermatte, 6340 Baar",
    factsheet: "",
    incidentalCosts: 90,
    state: "frei",
    moveInDate: null,
    floor: "3.OG",
    floorNum: 3,
    priceUnit: "CHF",
    rentalPrice: 2200,
    rentalPriceSquaremeterNet: 0,
    rentalPriceSquaremeter: 0,
    title: "W41_301",
    name: "41.301",
    rooms: 3.5,
    area: 100,
    virtualTourLink: "",
    balcony: 12,
    loggiaArea: 0,
    gardenSittingPlaceArea: 0,
    terraceArea: 0,
    basementArea: 10,
    parkingSpaceCost: 0,
    deposit: 0,
    reduitArea: 0,
    referenceNumber: "41.301",
  },
  {
    apartmentId: "W41_302",
    address: "Baarermatte, 6340 Baar",
    factsheet: "",
    incidentalCosts: 90,
    state: "frei",
    moveInDate: null,
    floor: "3.OG",
    floorNum: 3,
    priceUnit: "CHF",
    rentalPrice: 2200,
    rentalPriceSquaremeterNet: 0,
    rentalPriceSquaremeter: 0,
    title: "W41_302",
    name: "41.302",
    rooms: 3.5,
    area: 100,
    virtualTourLink: "",
    balcony: 12,
    loggiaArea: 0,
    gardenSittingPlaceArea: 0,
    terraceArea: 0,
    basementArea: 10,
    parkingSpaceCost: 0,
    deposit: 0,
    reduitArea: 0,
    referenceNumber: "41.302",
  },
  {
    apartmentId: "W42_301",
    address: "Baarermatte, 6340 Baar",
    factsheet: "",
    incidentalCosts: 90,
    state: "frei",
    moveInDate: null,
    floor: "3.OG",
    floorNum: 3,
    priceUnit: "CHF",
    rentalPrice: 2200,
    rentalPriceSquaremeterNet: 0,
    rentalPriceSquaremeter: 0,
    title: "W42_301",
    name: "42.301",
    rooms: 3.5,
    area: 100,
    virtualTourLink: "",
    balcony: 12,
    loggiaArea: 0,
    gardenSittingPlaceArea: 0,
    terraceArea: 0,
    basementArea: 10,
    parkingSpaceCost: 0,
    deposit: 0,
    reduitArea: 0,
    referenceNumber: "42.301",
  },
  {
    apartmentId: "W42_302",
    address: "Baarermatte, 6340 Baar",
    factsheet: "",
    incidentalCosts: 90,
    state: "frei",
    moveInDate: null,
    floor: "3.OG",
    floorNum: 3,
    priceUnit: "CHF",
    rentalPrice: 2200,
    rentalPriceSquaremeterNet: 0,
    rentalPriceSquaremeter: 0,
    title: "W42_302",
    name: "42.302",
    rooms: 3.5,
    area: 100,
    virtualTourLink: "",
    balcony: 12,
    loggiaArea: 0,
    gardenSittingPlaceArea: 0,
    terraceArea: 0,
    basementArea: 10,
    parkingSpaceCost: 0,
    deposit: 0,
    reduitArea: 0,
    referenceNumber: "42.302",
  },
  {
    apartmentId: "W43_301",
    address: "Baarermatte, 6340 Baar",
    factsheet: "",
    incidentalCosts: 90,
    state: "frei",
    moveInDate: null,
    floor: "3.OG",
    floorNum: 3,
    priceUnit: "CHF",
    rentalPrice: 2200,
    rentalPriceSquaremeterNet: 0,
    rentalPriceSquaremeter: 0,
    title: "W43_301",
    name: "43.301",
    rooms: 3.5,
    area: 100,
    virtualTourLink: "",
    balcony: 12,
    loggiaArea: 0,
    gardenSittingPlaceArea: 0,
    terraceArea: 0,
    basementArea: 10,
    parkingSpaceCost: 0,
    deposit: 0,
    reduitArea: 0,
    referenceNumber: "43.301",
  },
  {
    apartmentId: "W43_302",
    address: "Baarermatte, 6340 Baar",
    factsheet: "",
    incidentalCosts: 90,
    state: "frei",
    moveInDate: null,
    floor: "3.OG",
    floorNum: 3,
    priceUnit: "CHF",
    rentalPrice: 2200,
    rentalPriceSquaremeterNet: 0,
    rentalPriceSquaremeter: 0,
    title: "W43_302",
    name: "43.302",
    rooms: 3.5,
    area: 100,
    virtualTourLink: "",
    balcony: 12,
    loggiaArea: 0,
    gardenSittingPlaceArea: 0,
    terraceArea: 0,
    basementArea: 10,
    parkingSpaceCost: 0,
    deposit: 0,
    reduitArea: 0,
    referenceNumber: "43.302",
  },
  {
    apartmentId: "W41_401",
    address: "Baarermatte, 6340 Baar",
    factsheet: "",
    incidentalCosts: 90,
    state: "frei",
    moveInDate: null,
    floor: "4.OG",
    floorNum: 4,
    priceUnit: "CHF",
    rentalPrice: 2250,
    rentalPriceSquaremeterNet: 0,
    rentalPriceSquaremeter: 0,
    title: "W41_401",
    name: "41.401",
    rooms: 4.5,
    area: 100,
    virtualTourLink: "",
    balcony: 12,
    loggiaArea: 0,
    gardenSittingPlaceArea: 0,
    terraceArea: 0,
    basementArea: 10,
    parkingSpaceCost: 0,
    deposit: 0,
    reduitArea: 0,
    referenceNumber: "41.401",
  },
  {
    apartmentId: "W41_402",
    address: "Baarermatte, 6340 Baar",
    factsheet: "",
    incidentalCosts: 90,
    state: "frei",
    moveInDate: null,
    floor: "4.OG",
    floorNum: 4,
    priceUnit: "CHF",
    rentalPrice: 2250,
    rentalPriceSquaremeterNet: 0,
    rentalPriceSquaremeter: 0,
    title: "W41_402",
    name: "41.402",
    rooms: 4.5,
    area: 100,
    virtualTourLink: "",
    balcony: 12,
    loggiaArea: 0,
    gardenSittingPlaceArea: 0,
    terraceArea: 0,
    basementArea: 10,
    parkingSpaceCost: 0,
    deposit: 0,
    reduitArea: 0,
    referenceNumber: "41.402",
  },
  {
    apartmentId: "W42_401",
    address: "Baarermatte, 6340 Baar",
    factsheet: "",
    incidentalCosts: 90,
    state: "frei",
    moveInDate: null,
    floor: "4.OG",
    floorNum: 4,
    priceUnit: "CHF",
    rentalPrice: 2250,
    rentalPriceSquaremeterNet: 0,
    rentalPriceSquaremeter: 0,
    title: "W42_401",
    name: "42.401",
    rooms: 4.5,
    area: 100,
    virtualTourLink: "",
    balcony: 12,
    loggiaArea: 0,
    gardenSittingPlaceArea: 0,
    terraceArea: 0,
    basementArea: 10,
    parkingSpaceCost: 0,
    deposit: 0,
    reduitArea: 0,
    referenceNumber: "42.401",
  },
  {
    apartmentId: "W42_402",
    address: "Baarermatte, 6340 Baar",
    factsheet: "",
    incidentalCosts: 90,
    state: "frei",
    moveInDate: null,
    floor: "4.OG",
    floorNum: 4,
    priceUnit: "CHF",
    rentalPrice: 2250,
    rentalPriceSquaremeterNet: 0,
    rentalPriceSquaremeter: 0,
    title: "W42_402",
    name: "42.402",
    rooms: 4.5,
    area: 100,
    virtualTourLink: "",
    balcony: 12,
    loggiaArea: 0,
    gardenSittingPlaceArea: 0,
    terraceArea: 0,
    basementArea: 10,
    parkingSpaceCost: 0,
    deposit: 0,
    reduitArea: 0,
    referenceNumber: "42.402",
  },
  {
    apartmentId: "W43_401",
    address: "Baarermatte, 6340 Baar",
    factsheet: "",
    incidentalCosts: 90,
    state: "frei",
    moveInDate: null,
    floor: "4.OG",
    floorNum: 4,
    priceUnit: "CHF",
    rentalPrice: 2250,
    rentalPriceSquaremeterNet: 0,
    rentalPriceSquaremeter: 0,
    title: "W43_401",
    name: "43.401",
    rooms: 4.5,
    area: 100,
    virtualTourLink: "",
    balcony: 12,
    loggiaArea: 0,
    gardenSittingPlaceArea: 0,
    terraceArea: 0,
    basementArea: 10,
    parkingSpaceCost: 0,
    deposit: 0,
    reduitArea: 0,
    referenceNumber: "43.401",
  },
  {
    apartmentId: "W43_402",
    address: "Baarermatte, 6340 Baar",
    factsheet: "",
    incidentalCosts: 90,
    state: "frei",
    moveInDate: null,
    floor: "4.OG",
    floorNum: 4,
    priceUnit: "CHF",
    rentalPrice: 2250,
    rentalPriceSquaremeterNet: 0,
    rentalPriceSquaremeter: 0,
    title: "W43_402",
    name: "43.402",
    rooms: 4.5,
    area: 100,
    virtualTourLink: "",
    balcony: 12,
    loggiaArea: 0,
    gardenSittingPlaceArea: 0,
    terraceArea: 0,
    basementArea: 10,
    parkingSpaceCost: 0,
    deposit: 0,
    reduitArea: 0,
    referenceNumber: "43.402",
  },
  {
    apartmentId: "W41_501",
    address: "Baarermatte, 6340 Baar",
    factsheet: "",
    incidentalCosts: 90,
    state: "frei",
    moveInDate: null,
    floor: "5.OG",
    floorNum: 5,
    priceUnit: "CHF",
    rentalPrice: 2400,
    rentalPriceSquaremeterNet: 0,
    rentalPriceSquaremeter: 0,
    title: "W41_501",
    name: "41.501",
    rooms: 4.5,
    area: 110,
    virtualTourLink: "",
    balcony: 12,
    loggiaArea: 0,
    gardenSittingPlaceArea: 0,
    terraceArea: 0,
    basementArea: 10,
    parkingSpaceCost: 0,
    deposit: 0,
    reduitArea: 0,
    referenceNumber: "41.501",
  },
  {
    apartmentId: "W41_502",
    address: "Baarermatte, 6340 Baar",
    factsheet: "",
    incidentalCosts: 90,
    state: "frei",
    moveInDate: null,
    floor: "5.OG",
    floorNum: 5,
    priceUnit: "CHF",
    rentalPrice: 2400,
    rentalPriceSquaremeterNet: 0,
    rentalPriceSquaremeter: 0,
    title: "W41_502",
    name: "41.502",
    rooms: 4.5,
    area: 110,
    virtualTourLink: "",
    balcony: 12,
    loggiaArea: 0,
    gardenSittingPlaceArea: 0,
    terraceArea: 0,
    basementArea: 10,
    parkingSpaceCost: 0,
    deposit: 0,
    reduitArea: 0,
    referenceNumber: "41.502",
  },
  {
    apartmentId: "W42_501",
    address: "Baarermatte, 6340 Baar",
    factsheet: "",
    incidentalCosts: 90,
    state: "frei",
    moveInDate: null,
    floor: "5.OG",
    floorNum: 5,
    priceUnit: "CHF",
    rentalPrice: 2400,
    rentalPriceSquaremeterNet: 0,
    rentalPriceSquaremeter: 0,
    title: "W42_501",
    name: "42.501",
    rooms: 4.5,
    area: 110,
    virtualTourLink: "",
    balcony: 12,
    loggiaArea: 0,
    gardenSittingPlaceArea: 0,
    terraceArea: 0,
    basementArea: 10,
    parkingSpaceCost: 0,
    deposit: 0,
    reduitArea: 0,
    referenceNumber: "42.501",
  },
  {
    apartmentId: "W42_502",
    address: "Baarermatte, 6340 Baar",
    factsheet: "",
    incidentalCosts: 90,
    state: "frei",
    moveInDate: null,
    floor: "5.OG",
    floorNum: 5,
    priceUnit: "CHF",
    rentalPrice: 2400,
    rentalPriceSquaremeterNet: 0,
    rentalPriceSquaremeter: 0,
    title: "W42_502",
    name: "42.502",
    rooms: 4.5,
    area: 110,
    virtualTourLink: "",
    balcony: 12,
    loggiaArea: 0,
    gardenSittingPlaceArea: 0,
    terraceArea: 0,
    basementArea: 10,
    parkingSpaceCost: 0,
    deposit: 0,
    reduitArea: 0,
    referenceNumber: "42.502",
  },
  {
    apartmentId: "W43_501",
    address: "Baarermatte, 6340 Baar",
    factsheet: "",
    incidentalCosts: 90,
    state: "frei",
    moveInDate: null,
    floor: "5.OG",
    floorNum: 5,
    priceUnit: "CHF",
    rentalPrice: 2400,
    rentalPriceSquaremeterNet: 0,
    rentalPriceSquaremeter: 0,
    title: "W43_501",
    name: "43.501",
    rooms: 4.5,
    area: 110,
    virtualTourLink: "",
    balcony: 12,
    loggiaArea: 0,
    gardenSittingPlaceArea: 0,
    terraceArea: 0,
    basementArea: 10,
    parkingSpaceCost: 0,
    deposit: 0,
    reduitArea: 0,
    referenceNumber: "43.501",
  },
  {
    apartmentId: "W43_502",
    address: "Baarermatte, 6340 Baar",
    factsheet: "",
    incidentalCosts: 90,
    state: "frei",
    moveInDate: null,
    floor: "5.OG",
    floorNum: 5,
    priceUnit: "CHF",
    rentalPrice: 2400,
    rentalPriceSquaremeterNet: 0,
    rentalPriceSquaremeter: 0,
    title: "W43_502",
    name: "43.502",
    rooms: 4.5,
    area: 110,
    virtualTourLink: "",
    balcony: 12,
    loggiaArea: 0,
    gardenSittingPlaceArea: 0,
    terraceArea: 0,
    basementArea: 10,
    parkingSpaceCost: 0,
    deposit: 0,
    reduitArea: 0,
    referenceNumber: "43.502",
  },
  {
    apartmentId: "W11_401",
    address: "Baarermatte, 6340 Baar",
    factsheet: "",
    incidentalCosts: 90,
    state: "frei",
    moveInDate: null,
    floor: "4.OG",
    floorNum: 4,
    priceUnit: "CHF",
    rentalPrice: 2400,
    rentalPriceSquaremeterNet: 0,
    rentalPriceSquaremeter: 0,
    title: "W11_401",
    name: "11.401",
    rooms: 4.5,
    area: 110,
    virtualTourLink: "",
    balcony: 12,
    loggiaArea: 0,
    gardenSittingPlaceArea: 0,
    terraceArea: 0,
    basementArea: 10,
    parkingSpaceCost: 0,
    deposit: 0,
    reduitArea: 0,
    referenceNumber: "11.401",
  },
  {
    apartmentId: "W11_301",
    address: "Baarermatte, 6340 Baar",
    factsheet: "",
    incidentalCosts: 90,
    state: "frei",
    moveInDate: null,
    floor: "3.OG",
    floorNum: 3,
    priceUnit: "CHF",
    rentalPrice: 2400,
    rentalPriceSquaremeterNet: 0,
    rentalPriceSquaremeter: 0,
    title: "W11_301",
    name: "11.301",
    rooms: 4.5,
    area: 110,
    virtualTourLink: "",
    balcony: 12,
    loggiaArea: 0,
    gardenSittingPlaceArea: 0,
    terraceArea: 0,
    basementArea: 10,
    parkingSpaceCost: 0,
    deposit: 0,
    reduitArea: 0,
    referenceNumber: "11.301",
  },
  {
    apartmentId: "W11_201",
    address: "Baarermatte, 6340 Baar",
    factsheet: "",
    incidentalCosts: 90,
    state: "frei",
    moveInDate: null,
    floor: "2.OG",
    floorNum: 2,
    priceUnit: "CHF",
    rentalPrice: 2400,
    rentalPriceSquaremeterNet: 0,
    rentalPriceSquaremeter: 0,
    title: "W11_201",
    name: "11.201",
    rooms: 4.5,
    area: 110,
    virtualTourLink: "",
    balcony: 12,
    loggiaArea: 0,
    gardenSittingPlaceArea: 0,
    terraceArea: 0,
    basementArea: 10,
    parkingSpaceCost: 0,
    deposit: 0,
    reduitArea: 0,
    referenceNumber: "11.201",
  },

  {
    apartmentId: "W13_201",
    address: "Baarermatte, 6340 Baar",
    factsheet: "",
    incidentalCosts: 90,
    state: "frei",
    moveInDate: null,
    floor: "2.OG",
    floorNum: 2,
    priceUnit: "CHF",
    rentalPrice: 2400,
    rentalPriceSquaremeterNet: 0,
    rentalPriceSquaremeter: 0,
    title: "W13_201",
    name: "13.201",
    rooms: 4.5,
    area: 110,
    virtualTourLink: "",
    balcony: 12,
    loggiaArea: 0,
    gardenSittingPlaceArea: 0,
    terraceArea: 0,
    basementArea: 10,
    parkingSpaceCost: 0,
    deposit: 0,
    reduitArea: 0,
    referenceNumber: "13.201",
  },
  {
    apartmentId: "W11_101",
    address: "Baarermatte, 6340 Baar",
    factsheet: "",
    incidentalCosts: 90,
    state: "frei",
    moveInDate: null,
    floor: "1.OG",
    floorNum: 1,
    priceUnit: "CHF",
    rentalPrice: 2400,
    rentalPriceSquaremeterNet: 0,
    rentalPriceSquaremeter: 0,
    title: "W11_101",
    name: "11.101",
    rooms: 4.5,
    area: 110,
    virtualTourLink: "",
    balcony: 12,
    loggiaArea: 0,
    gardenSittingPlaceArea: 0,
    terraceArea: 0,
    basementArea: 10,
    parkingSpaceCost: 0,
    deposit: 0,
    reduitArea: 0,
    referenceNumber: "11.101",
  },
  {
    apartmentId: "W12_001",
    address: "Baarermatte, 6340 Baar",
    factsheet: "",
    incidentalCosts: 90,
    state: "frei",
    moveInDate: null,
    floor: "EG",
    floorNum: 0,
    priceUnit: "CHF",
    rentalPrice: 2400,
    rentalPriceSquaremeterNet: 0,
    rentalPriceSquaremeter: 0,
    title: "W12_001",
    name: "12.001",
    rooms: 4.5,
    area: 110,
    virtualTourLink: "",
    balcony: 12,
    loggiaArea: 0,
    gardenSittingPlaceArea: 0,
    terraceArea: 0,
    basementArea: 10,
    parkingSpaceCost: 0,
    deposit: 0,
    reduitArea: 0,
    referenceNumber: "12.001",
  },
];

export const findDuplicateApartmentIds = (
  apartments: Apartment[]
): string[] | true => {
  const seen = new Set<string>();
  const duplicates = new Set<string>();

  for (const apartment of apartments) {
    if (seen.has(apartment.apartmentId)) {
      duplicates.add(apartment.apartmentId);
    } else {
      seen.add(apartment.apartmentId);
    }
  }

  return duplicates.size > 0 ? Array.from(duplicates) : true;
};
